CREATE TABLE EVENTS (
  id SERIAL PRIMARY KEY,
  task_id INTEGER NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  message JSONB NOT NULL,
  date_created TIMESTAMP NOT NULL
);

CREATE TABLE SUMMARY (
  task_id SERIAL PRIMARY KEY,
  payload JSONB NOT NULL
);

CREATE INDEX IDX_TASK_ID ON EVENTS (task_id);